import Navigation from "@/components/Navigation"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function OnBoardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <main className="flex items-center justify-center min-h-screen">
        {children}
      </main>

      {/* this would not be rerendered  */}
      <Navigation />
    </>
  )
}
